failure notification

diff --git a/.github/workflows/workflow3.yml b/.github/workflows/workflow3.yml
--- a/.github/workflows/workflow3.yml
+++ b/.github/workflows/workflow3.yml
@@ -10,7 +10,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: step1
-        continue-on-error: true
+         ##continue-on-error: true
         run: |
           eo "test step 1"
           sleep 10
@@ -18,26 +18,35 @@ jobs:
         run: echo "step2 run"
       - name: step3
         run: echo "step3 run"
-  test1: 
-    runs-on: ubuntu-latest
-    needs: build
-    steps:
-      - name: step 1
-        run: |
-          echo "test step1 "
-          sleep 10
-  test2: 
-    runs-on: ubuntu-latest
-    needs: 
-      - build
-      - build2
-    steps:
-      - name: step 1
-        run: |
-          echo "test step1 "
-          sleep 10
-
+        
   build2:
+    runs-on: ubuntu-latest
+    steps:
+      - name: step1
+        run: |
+          echo "test step 1"
+          sleep 10
+          
+  ##test1: 
+  ##  runs-on: ubuntu-latest
+    ##needs: build
+    ##steps:
+      ##- name: step 1
+        ##run: |
+          ##echo "test step1 "
+          ##sleep 10
+  ##test2: 
+    #runs-on: ubuntu-latest
+    #needs: 
+     # - build
+      #- build2
+    #steps:
+     # - name: step 1
+      #  run: |
+       #   echo "test step1 "
+        #  sleep 10
+
+  full-test:
     runs-on: ubuntu-latest
     steps:
       - name: step1
@@ -47,10 +56,20 @@ jobs:
           
   deploy:
     runs-on: ubuntu-latest
-    needs: test1
-    if: ${{ always() }}
+    needs: full-test
+    #if: ${{ always() }}
     steps:
       - name: step 1 
         run: |
           echo "test step 1"
             sleep 10
+
+  notification:
+    runs-on: ubuntu-latest
+    needs: build
+    if: ${{ needs.build.result == 'failure' || failure() }}
+    steps:
+      - name: notify
+        run: |
+          echo "Build step failed"
+          slepp 10
